# SIB - Portfolio of Machine Learning Algorithms

## Exercise 12 - Dropout layer

A dropout layer in neural networks (NNs) is a regularization technique where a random set of neurons is temporarily ignored (dropped out) during training. This helps prevent overfitting by promoting robustness and generalization in the model.



### 12.1) 
Add a new layer named Dropout to the layers module; Take into consideration the following structure:

class Dropout(Layer):
- arguments:
  - probability – the dropout rate, between 0 and 1
- estimated parameters:
  - mask – binomial mask that sets some inputs to 0 based on the probability
  - input – the input of the layer
  - output – the output of the layer
- methods:
  - forward_propagation – performs forward propagation on the given input, i.e., applies the mask to the input and scales it when in training mode; does nothing in inference mode (returns the input as is)
  - backward_propagation – performs backward propagation on the given error, i.e., multiplies the received error by the mask
  - output_shape – returns the input shape (dropout does not change the shape of the data)
  - parameters – returns 0 (dropout layers do not have learnable parameters)

---

Dropout.forward_propagation:
- arguments:
  - input – input array
  - training – boolean indicating whether we are in training or inference mode
- algorithm:
  1. If we are in training mode:
     - Compute the scaling factor: `scaling_factor = 1 / (1 – probability)`
     - Compute the mask using a binomial distribution with probability `1 – probability` and size equal to the input
     - Compute the output: `output = input * mask * scaling_factor`
     - Return the output
  2. If we are in inference mode:
     - Return the input (input is not changed during inference)

---

Dropout.backward_propagation:
- arguments:
  - output_error – the output error of the layer
- algorithm:
  - Multiply the `output_error` by the `mask` and return it

---

Dropout.output_shape:
- Returns the input shape

---

Dropout.parameters:
- Returns 0

### 12.2) 
Test the layer with a random input and check if the output shows the desired behavior.


In [ ]:
from si.neural_networks.layers import Dropout
import numpy as np

In [ ]:
from si.neural_networks.layers import Dropout
import numpy as np
probability = 0.5  # Dropout rate (50%)
input_data = np.random.randn(3, 3)  # Random input (3x3)

# Create Dropout layer
dropout_layer = Dropout(probability=probability)

# Test during training
print("Training:")
output_train = dropout_layer.forward_propagation(input_data, training=True)
print("Input:")
print(input_data)
print("Output with Dropout:")
print(output_train)
print("Applied Mask:")
print(dropout_layer.mask)

# Test during inference (without dropout)
print("\nInference:")
output_infer = dropout_layer.forward_propagation(input_data, training=False)
print("Input:")
print(input_data)
print("Output with Dropout (no change):")
print(output_infer)

Training:
Input:
[[ 0.59409987  2.99990412  2.79225544]
 [-1.08594183 -0.28161022  0.67585272]
 [ 0.72023149  0.52827755  1.63405624]]
Output with Dropout:
[[ 0.          5.99980823  0.        ]
 [-2.17188366 -0.          1.35170544]
 [ 0.          1.05655509  0.        ]]
Applied Mask:
[[0 1 0]
 [1 0 1]
 [0 1 0]]

Inference:
Input:
[[ 0.59409987  2.99990412  2.79225544]
 [-1.08594183 -0.28161022  0.67585272]
 [ 0.72023149  0.52827755  1.63405624]]
Output with Dropout (no change):
[[ 0.59409987  2.99990412  2.79225544]
 [-1.08594183 -0.28161022  0.67585272]
 [ 0.72023149  0.52827755  1.63405624]]


Conseguimos ver que após a aplicação da máscara, durante o treino a saída, passe a ter neurónios desativados (0) e ativados, enquanto que no processo de inferência isso não acontece... Os tamanhos das entradas e saídas são iguais