# SIB - Portfolio of Machine Learning Algorithms

## Exercise 1: NumPy array Indexing/Slicing

### 1.1) 
In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [1]:
from si.io.csv_file import read_csv
#iris = read_csv("C:/Users/dases/Desktop/SI/repositorio/si/datasets/iris/iris.csv",)
iris = read_csv("../datasets/iris/iris.csv", features=True, label=True)
print("Shape of iris dataset:",iris.shape())
print("Features:", iris.features)
print("Label:", iris.label)
print(iris.X)

Shape of iris dataset: (150, 4)
Features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
Label: class
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.

### 1.2)
Select the penultimate independent variable. What is the dimension of the resulting array?

In [2]:
pen_variable = iris.X[:,-2]
print("N. of dimensions:",pen_variable.ndim)
print("Shape", pen_variable.shape)

N. of dimensions: 1
Shape (150,)


### 1.3)
Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [3]:
last_ten_samples = iris.X[-10:,:]
means= last_ten_samples.mean(axis=0)
print(means)

[6.45 3.03 5.33 2.17]


### 1.4) 
Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?

In [4]:
import numpy as np
mask_samples = np.all(iris.X <= 6, axis=1)
filtered_samples = iris.X[mask_samples,:]
print("Number of samples:",filtered_samples.shape[0])   

Number of samples: 89


### 1.5) 
Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [5]:
mask_not_iris_setosa = iris.y != "Iris-setosa"
samples_wo_setosa = iris.X[mask_not_iris_setosa,:]
print("Number of samples:",samples_wo_setosa.shape[0])

Number of samples: 100


## Exercise 2: NumPy array Indexing/Slicing

### 2.1) 

Add a method to the Dataset class that removes all samples containing at least one null value (NaN). Note that the resulting object should not contain null values in any independent feature/variable. Also, note that you should update the y vector by removing entries associated with the samples to be removed. You should use only NumPy functions.  

Method name: dropna  

- def dropna  

    - arguments:  
        - none  
    - expected output:  
        - self (modified Dataset object)

### 2.2) 
Add a method to the Dataset class that replaces all null values with another value or the mean or median of the feature/variable. Note that the resulting object should not contain null values in any independent feature/variable. You should use only NumPy functions.  

Method name: fillna  

- def fillna  

    - arguments:
        - value – float or "mean" or "median"
    - expected output:
        - self (modified Dataset object)

### 2.3) 
Add a method to the Dataset class that removes a sample by its index. Note that you should also update the y vector by removing the entry associated with the sample to be removed. You should use only NumPy functions.  

Method name: remove_by_index  

- def remove_by_index  

    - arguments:
        - index – integer corresponding to the sample to remove
    - expected output:
        - self (modified Dataset object)

### Optional 
You can add examples of how to use these methods to the script/notebook of Exercise 1.

In [6]:
# Since iris as no NaN values, I introduced NaN values for testing
iris.X[0, 0] = np.nan  
iris.X[5, 1] = np.nan  

# Display initial shape and data
print("Shape of iris dataset with NaNs:", iris.X.shape)

# Example 1: Remove samples with NaN values
iris_cleaned = iris.dropna()
print("Shape after dropna:", iris_cleaned.X.shape)  # Should be (148, 4)


Shape of iris dataset with NaNs: (150, 4)
Shape after dropna: (148, 4)


In [7]:
iris = read_csv("../datasets/iris/iris.csv", features=True, label=True)

# Introduce NaN values for testing
iris.X[10, 2] = np.nan  
iris.X[15, 3] = np.nan  

# Check for NaNs before filling, should be 2 (we introduced NaN values for testing)
initial_nans = np.isnan(iris.X).sum()
print("Initial NaNs in the dataset:", initial_nans)

# Fill NaN values with a specific value
iris_filled_value = iris.fillna(0.0)  
print("NaNs after filling with 0.0:", np.isnan(iris_filled_value.X).sum())

# Fill NaN values with the column-wise mean
iris_filled_mean = iris.fillna("MEAN") 
print("NaNs after filling with column means:", np.isnan(iris_filled_mean.X).sum())

# Fill NaN values with the column-wise median
iris_filled_median = iris.fillna("MEDIAN")  
print("NaNs after filling with column medians:", np.isnan(iris_filled_median.X).sum())


Initial NaNs in the dataset: 2
NaNs after filling with 0.0: 0
NaNs after filling with column means: 0
NaNs after filling with column medians: 0


In [8]:
iris = read_csv("../datasets/iris/iris.csv", features=True, label=True)

# Display initial shape and data
print("Initial shape of iris dataset:", iris.X.shape)

# Remove the sample from index 5
index_to_remove = 5 
iris_after_removal = iris.remove_by_index(index_to_remove)
print("Shape after removing sample at index 5:", iris_after_removal.X.shape)  # Should be (149, 4)

# Verify that the sample has been removed
print("Removed sample data:", iris.X[index_to_remove] if index_to_remove < iris.X.shape[0] else "Sample removed")


Initial shape of iris dataset: (150, 4)
Shape after removing sample at index 5: (149, 4)
Removed sample data: [4.6 3.4 1.4 0.3]


## Exercise 3: Implementing SelectPercentile

### 3.1) 
Add the SelectPercentile object to the feature_selection sub-package. You should create a module called "select_percentile.py" to implement this object. The SelectPercentile class has a similar architecture to the SelectKBest class. Consider the structure presented:  

- class SelectPercentile(Transformer):
    - parameters:
        - score_func – variance analysis function (f_classification by default)
        - percentile – percentile for selecting features
    - estimated parameters:
        - F – the F value for each feature estimated by the score_func
        - p – the p value for each feature estimated by the score_func
    - methods:
        - _fit – estimates the F and p values for each feature using the scoring_func; returns itself (self)
        - _transform – selects features with the highest F value up to the specified percentile. For example, for a dataset with 10 features and a percentile of 50% your transform should select the top 5 features with the highest F value. Returns the transformed Dataset object.

### 3.3) 
Test the SelectPercentile class in a Jupyter notebook using the "iris.csv" dataset (classification).

In [9]:
import numpy as np
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.f_classification import f_classification

# 'iris' is defined again because of previous solved optional exercise:
iris = read_csv("../datasets/iris/iris.csv", features=True, label=True)

# Initialize SelectPercentile
percentile = 50
selector = SelectPercentile(score_func=f_classification, percentile=percentile)

# Fit the selector
selector.fit(iris)

# Transform the dataset
new_iris = selector.transform(iris)

# Display results
print("Original features:", iris.features)
print("Selected features:", new_iris.features)
print("Original shape:", iris.X.shape)
print("New shape:", new_iris.X.shape)


Original features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
Selected features: ['petal_length', 'petal_width']
Original shape: (150, 4)
New shape: (150, 2)
